kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30007 # This MUST match the nodePort in your service.yaml
    hostPort: 8081       # Port you'll use on localhost to access the service
    listenAddress: "0.0.0.0" 
    protocol: TCP 